import { buildMetadata } from "@/lib/seo";
import { LegalSection, LegalDocLayout } from "@/components/legal-section";

export const metadata = buildMetadata({
  title: "Terms of Service — Trimora Systems",
  description: "The terms governing use of Trimora Systems products, including Trimora POS and Trimora AI.",
  path: "/legal/terms",
});

const EFFECTIVE_DATE = "5 July 2026";

const SECTIONS = [
  {
    heading: "1. Introduction and Acceptance of Terms",
    body: [
      "These Terms of Service (\u201cTerms\u201d) govern access to and use of any product, service, website, application, application programming interface (API), or platform operated by Trimora Systems Limited (\u201cTrimora\u201d, \u201cwe\u201d, \u201cour\u201d, or \u201cus\u201d), including Trimora POS, the Trimora Intelligence Platform (branded as \u201cTrimora AI\u201d), and any future Trimora product (collectively, the \u201cServices\u201d).",
      "By creating an account, accessing, or using the Services, you (\u201cyou\u201d, \u201cCustomer\u201d, or \u201cUser\u201d) agree to be bound by these Terms. If you are accepting these Terms on behalf of a business, you confirm that you have the authority to bind that business, and \u201cyou\u201d refers to that business.",
      "If you do not agree to these Terms, do not access or use the Services.",
    ],
  },
  {
    heading: "2. Definitions",
    list: [
      "\u201cAccount\u201d means the Trimora account created by a Customer to access the Services.",
      "\u201cCustomer Data\u201d means any data, records, or content submitted, uploaded, or generated by a Customer through the Services, including customer records, appointments, inventory, sales, and reports.",
      "\u201cSubscription\u201d means the paid plan under which a Customer accesses the Services.",
      "\u201cAuthorized User\u201d means an employee, contractor, or staff member permitted by the Customer to access the Services under the Customer's Account.",
    ],
  },
  {
    heading: "3. Description of Services",
    body: [
      "Trimora provides business management software for small and medium-sized businesses, currently including point-of-sale, booking, inventory, and analytics functionality (\u201cTrimora POS\u201d) and an AI-assisted business insights interface (\u201cTrimora AI\u201d). Trimora may introduce, modify, or discontinue features, products, or modules at its discretion, and will provide reasonable notice of material changes affecting active Subscriptions where practicable.",
    ],
  },
  {
    heading: "4. Eligibility",
    body: [
      "The Services are intended for use by businesses and their Authorized Users, and are not directed at individual consumers acting outside a business capacity. You must be at least 18 years old and legally capable of entering into a binding contract to create an Account.",
    ],
  },
  {
    heading: "5. Account Registration and Security",
    body: [
      "You agree to provide accurate, current, and complete information when creating an Account, and to keep this information up to date. You are responsible for maintaining the confidentiality of your Account credentials, including staff PINs and login details, and for all activity that occurs under your Account, whether or not authorized by you.",
      "You must notify Trimora promptly at support@trimorasystems.com if you become aware of any unauthorized access to or use of your Account.",
    ],
  },
  {
    heading: "6. Subscription Plans, Fees, and Payment",
    body: [
      "Access to the Services is provided on a subscription basis. Applicable fees, billing frequency, and plan features are as described at the time of purchase or as otherwise agreed in writing.",
    ],
    list: [
      "Fees are payable in advance for each billing period unless otherwise agreed.",
      "Payments may be processed via M-Pesa or other payment methods made available by Trimora from time to time. Trimora does not store payment credentials such as M-Pesa PINs, and payment processing is subject to the terms of the relevant payment provider.",
      "Except as required by law or as otherwise stated in these Terms, fees are non-refundable.",
      "Trimora may change Subscription fees on renewal with reasonable prior notice. Continued use of the Services after a fee change takes effect constitutes acceptance of the new fee.",
      "Failure to pay applicable fees may result in suspension or termination of access to the Services, subject to Section 18.",
    ],
  },
  {
    heading: "7. Free Trials and Promotions",
    body: [
      "Trimora may offer free trials or promotional pricing at its discretion. Trimora reserves the right to determine eligibility for any trial or promotion and to modify or terminate such offers at any time. At the end of a free trial, continued use of the Services may require an active paid Subscription.",
    ],
  },
  {
    heading: "8. Customer Data and Ownership",
    body: [
      "As between Trimora and the Customer, the Customer retains all ownership rights in Customer Data. Trimora does not claim ownership of Customer Data, including customer records, inventory, appointments, sales, or reports uploaded to the Services.",
      "By using the Services, the Customer grants Trimora a limited, non-exclusive license to access, host, process, and use Customer Data solely as necessary to provide, maintain, secure, and improve the Services, and as described in Trimora's Privacy Policy.",
      "Customers are responsible for ensuring they have the necessary rights and consents to submit any personal data of their own customers or staff into the Services, and for their own compliance with applicable data protection law in respect of such data.",
    ],
  },
  {
    heading: "9. Acceptable Use",
    body: ["You agree not to use the Services to:"],
    list: [
      "Violate any applicable law or regulation",
      "Infringe the intellectual property, privacy, or other rights of any third party",
      "Upload or transmit malicious code, or attempt to gain unauthorized access to the Services or related systems",
      "Interfere with or disrupt the integrity or performance of the Services",
      "Reverse engineer, decompile, or attempt to extract the source code of the Services, except to the extent permitted by law",
      "Resell, sublicense, or provide the Services to third parties outside your own business without Trimora's prior written consent",
      "Use the Services to process payment card data in a manner inconsistent with applicable card network rules",
    ],
    footnote: "Trimora reserves the right to investigate and take appropriate action, including suspension or termination, against any use that violates this Section.",
  },
  {
    heading: "10. Artificial Intelligence Features",
    body: [
      "Certain Services, including Trimora AI, use artificial intelligence and machine learning, including third-party AI models, to generate insights, automate workflows, and respond to natural-language queries. AI-generated outputs are provided for informational and operational assistance and may not always be accurate or complete.",
      "You are responsible for reviewing AI-generated outputs before relying on them for business, financial, or compliance decisions. Trimora is not liable for decisions made solely on the basis of AI-generated content.",
    ],
  },
  {
    heading: "11. Third-Party Services and Integrations",
    body: [
      "The Services may integrate with or rely on third-party providers, including cloud infrastructure, payment processors, messaging providers, and AI providers. Trimora is not responsible for the acts, omissions, availability, or performance of third-party services, which are governed by their own terms and policies.",
    ],
  },
  {
    heading: "12. Intellectual Property",
    body: [
      "The Services, including all software, design, text, graphics, logos, and underlying technology, are the property of Trimora Systems Limited or its licensors and are protected by applicable intellectual property laws. These Terms do not grant you any right, title, or interest in the Services except the limited right to use them in accordance with these Terms.",
      "Any feedback, suggestions, or ideas you provide about the Services may be used by Trimora without restriction or obligation to you.",
    ],
  },
  {
    heading: "13. Service Availability and Support",
    body: [
      "Trimora will use reasonable efforts to maintain the availability of the Services but does not guarantee uninterrupted or error-free operation. Scheduled maintenance, third-party outages, or circumstances beyond Trimora's reasonable control may affect availability.",
      "Support is available by email at support@trimorasystems.com, Monday to Friday, 8:00 AM–5:00 PM East Africa Time, excluding Kenyan public holidays. Critical incidents affecting multiple customers are prioritized outside these hours where reasonably possible. Support channels and hours may expand over time as Trimora grows, without requiring an update to these Terms.",
    ],
  },
  {
    heading: "14. Confidentiality",
    body: [
      "Each party agrees to protect the other party's confidential information disclosed in connection with the Services using the same degree of care it uses to protect its own confidential information of a similar nature, and not less than reasonable care, and not to disclose such information to third parties except as necessary to perform its obligations or as required by law.",
    ],
  },
  {
    heading: "15. Disclaimers",
    body: [
      "Except as expressly stated in these Terms, the Services are provided \u201cas is\u201d and \u201cas available\u201d, without warranties of any kind, whether express, implied, or statutory, including implied warranties of merchantability, fitness for a particular purpose, or non-infringement, to the maximum extent permitted by applicable law.",
    ],
  },
  {
    heading: "16. Limitation of Liability",
    body: [
      "To the maximum extent permitted by applicable law, Trimora shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, or business opportunity, arising out of or related to your use of the Services.",
      "Trimora's total aggregate liability arising out of or relating to these Terms or the Services shall not exceed the total fees paid by the Customer to Trimora in the twelve (12) months preceding the event giving rise to the claim.",
    ],
  },
  {
    heading: "17. Indemnification",
    body: [
      "You agree to indemnify and hold harmless Trimora Systems Limited, its officers, employees, and agents from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising from your use of the Services, your violation of these Terms, or your violation of any applicable law or third-party right.",
    ],
  },
  {
    heading: "18. Suspension and Termination",
    body: [
      "Trimora may suspend or terminate access to the Services, with notice where reasonably practicable, if a Customer breaches these Terms, fails to pay applicable fees, or where Trimora reasonably believes suspension is necessary to protect the security or integrity of the Services or other users.",
      "A Customer may terminate its Subscription in accordance with the cancellation process made available within the Services or by written notice to support@trimorasystems.com. Termination does not entitle the Customer to a refund of prepaid fees except as required by law or otherwise agreed.",
    ],
  },
  {
    heading: "19. Data Export and Retention on Termination",
    body: [
      "Customers may request an export of their Customer Data at any time while their account is active. Following termination of a Subscription, the Customer has 30 days to request a data export, unless a longer retention period is required by law. After the applicable retention period expires, Trimora may delete Customer Data in accordance with its data retention practices.",
    ],
  },
  {
    heading: "20. Governing Law and Dispute Resolution",
    body: [
      "These Terms are governed by the laws of the Republic of Kenya, without regard to conflict of law principles. The parties agree to first attempt to resolve any dispute arising out of or relating to these Terms through good-faith negotiation. If a dispute is not resolved through negotiation, the parties will attempt mediation before proceeding to litigation, where appropriate. If mediation fails or is unsuitable, the dispute shall be submitted to the competent courts of Kenya.",
    ],
  },
  {
    heading: "21. Changes to These Terms",
    body: [
      "Trimora may update these Terms from time to time. Material changes will be communicated through appropriate channels, such as email or an in-product notice, where required by law or where the change materially affects Customer rights. Continued use of the Services after changes take effect constitutes acceptance of the revised Terms. The latest version will always be available at trimorasystems.com/legal/terms.",
    ],
  },
  {
    heading: "22. General Provisions",
    list: [
      "Entire Agreement: These Terms, together with the Privacy Policy and any order form or written agreement referencing these Terms, constitute the entire agreement between the parties regarding the Services.",
      "Severability: If any provision of these Terms is found unenforceable, the remaining provisions will remain in full force and effect.",
      "Assignment: You may not assign these Terms without Trimora's prior written consent. Trimora may assign these Terms in connection with a merger, acquisition, or sale of assets.",
      "Force Majeure: Neither party shall be liable for delays or failures in performance resulting from causes beyond its reasonable control.",
      "No Waiver: Failure to enforce any provision of these Terms shall not constitute a waiver of that provision.",
      "Notices: Notices to Trimora should be sent to support@trimorasystems.com. Notices to the Customer may be sent to the email address associated with the Account.",
    ],
  },
  {
    heading: "23. Contact Us",
    body: ["Trimora Systems Limited", "Website: trimorasystems.com", "Email: support@trimorasystems.com"],
  },
];

export default function Page() {
  return (
    <LegalDocLayout title="Terms of Service" effectiveDate={EFFECTIVE_DATE}>
      {SECTIONS.map((section) => (
        <LegalSection key={section.heading} {...section} />
      ))}
    </LegalDocLayout>
  );
}
